services:
  - type: web
    name: uam-system-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: dpg-d0n0tradbo4c73eftge0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres_backend_kfwx
      - key: DB_USERNAME
        value: postgres_backend_kfwx_user
      - key: DB_PASSWORD
        value: j3xP8RfKlcAbtoEt1iVbDu0rTTVi1
      - key: JWT_SECRET
        value: your_super_secret_jwt_key
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: ADMIN_EMAIL
        value: mutavakkilukhan4428@gmail.com
      - key: ADMIN_NAME
        value: Mutavakkil
      - key: ADMIN_PASSWORD
        value: Muttu@123
      - key: MANAGER_EMAIL
        value: mutavakkilmuttu@gmail.com
      - key: MANAGER_NAME
        value: Mr.khan
      - key: MANAGER_PASSWORD
        value: Muttu@123
      - key: PORT
        value: 3000 
