services:
  # Frontend Service
  - type: web
    name: frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://user-management-system-backend.onrender.com

  # Backend Service
  - type: web
    name: backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: DB_HOST
        value: dpg-d0n0tradbo4c73eftge0-a
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        value: postgres_backend_hkvq_user
      - key: DB_PASSWORD
        value: jXs9PRKrNQeAXbtcQE1lYwDDw7cTTVli
      - key: DB_DATABASE
        value: uam-system-db
      - key: JWT_SECRET
        value: UAM_System_Secret_Key_2024_Secure_JWT_Token
      - key: ADMIN_EMAIL
        value: admin@uam.com
      - key: ADMIN_NAME
        value: System Admin
      - key: ADMIN_PASSWORD
        value: Admin@UAM2024
      - key: MANAGER_EMAIL
        value: manager@uam.com
      - key: MANAGER_NAME
        value: System Manager
      - key: MANAGER_PASSWORD
        value: Manager@UAM2024
      - key: PORT
        value: 3000
      - key: ALLOWED_ORIGINS
        value: https://user-management-system-frontend.onrender.com 
